numpy array will have elements of same type.and these elements are stored in very compact way. numpy code is written in c++ so it's actually very fast .

More formally , it is a library in python for adding support for large , multidimensional array along with high level maths operation to operate in these arrays.

In [1]:
import math as m
m.sqrt(10)

3.1622776601683795

In [2]:
import numpy as np

In [3]:
l=[1,2,3]
a=np.array(l)
print(a)
k=[1,2,'3']
b=np.array(k)
print(b)
print(b.shape) #imp
np.arange(10)

[1 2 3]
['1' '2' '3']
(3,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a=np.zeros(10)
print(a.dtype)
a[0]=1
a
#np.ones(10)

float64


array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
b= np.zeros((2,3,2)) # 2d array of dim. 3*2
b

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [5]:
b[0][1][1]

0.0

In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]]);
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#subarry in grid
b=a[:,0] # ':' denotes all and 0 denotes coloumn 0 
print(b)
c=a[0:2,0]  # int 0th coloumn 0 and 1 st row
print(c)
d=a[0,0:2]   # in 0th roe 0 and 1 st coloumn
print(d)
e=a[:,0:2]   # in all row 0 and 1st column
print(e)


[1 4 7]
[1 4]
[1 2]
[[1 2]
 [4 5]
 [7 8]]


<font color=red size=5>operations</font>

In [8]:
a=np.array([1,3,4])
b=np.array([2,1,5])
print(a+2,a*2,a/2,a**2,a**1/2) # operations each in a
print(a+b) #  add a nd b index wise (if sizes r equal)
print(a**b)


[3 5 6] [2 6 8] [0.5 1.5 2. ] [ 1  9 16] [0.5 1.5 2. ]
[3 4 9]
[   1    3 1024]


In [9]:
a.mean()
a.sum()

8

In [10]:
# let's say we have to find distance btw x and y
x=np.array([1,2,3])
y=np.array([2,4,1])
d=((x-y)**2) # (x1-x2)^2 , (y1-y2)^2 , .....
dist = m.sqrt(d.sum())
print(dist)

3.0


In [11]:
# we have to find summm.(xi-xmean)^2
x=np.array([1,3,5,6])
y= x-x.mean() # (1-xmean,3-xmean,.....)
diff= (y**2).sum()
print(diff)

14.75


In [12]:
# Dot product
a1=np.array([[1,2],[3,4]])
a2=np.array([[10,20],[30,40]])
c=a1.dot(a2)
print(c)

[[ 70 100]
 [150 220]]


In [13]:
# sum of first row in c
np.sum(c[0,:])

170

In [14]:
#colum wise sum
np.sum(c,axis=0)

array([220, 320])

In [15]:
# Row wise sum
np.sum(c,axis=1)

array([170, 370])

In [16]:
#Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:
a=np.random.randn(2)
b=np.random.randn(2,3)
print(a)
print(b)

[-0.56652145 -0.93004335]
[[-0.80337704  0.53267486 -0.45021742]
 [ 1.89752071 -0.18262256  1.51496028]]


In [112]:
#Following will randomly sample 10 values in the interval [1, 100)
np.random.randint(1,100,10)

array([ 2, 14, 80, 60,  7, 98, 71, 32, 37, 10])